language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"

addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_script:
  - npm i
  - node_modules/.bin/usdocker --refresh
  - node_modules/.bin/usdocker mysql up
  - node_modules/.bin/usdocker mongodb up
  - pecl istall mongodb

install:
  - composer install

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/PdoMySqlTest.php
  - phpunit testsdb/MongoDbDriverTest.php

