language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"

addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_script:
  - npm i
  - node_modules/.bin/usdocker --refresh
  - node_modules/.bin/usdocker -v mysql up --dump
  - node_modules/.bin/usdocker -v mongodb up
  - pecl istall mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - docker ps

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/PdoMySqlTest.php
  - phpunit testsdb/MongoDbDriverTest.php

