language: php
php:
  - "7.1"

env:
  - MYSQL_PASSWORD=.
  - PSQL_PASSWORD=.

addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_script:
  - npm i
  - node_modules/.bin/usdocker --refresh
  - pecl istall mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install pdo_pgsql
  - echo "extension = pdo_pgsql.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - docker ps

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/MongoDbDriverTest.php
  - phpunit testsdb/PdoMySqlTest.php
  - phpunit testsdb/PdoPostgresTest.php
