language: php
php:
  - "7.1"
#  - "7.0"
#  - "5.6"


addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_install:
#  - mysql -u root -e "CREATE USER 'root'@'mysql-container' IDENTIFIED BY 'password';"
#  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'mysql-container';"
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password')"

install:
  - php -i
  - composer install
  - npm i
  - node_modules/.bin/usdocker --refresh
  - node_modules/.bin/usdocker -v mongodb up --dump
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/MongoDbDriverTest.php
  - phpunit testsdb/PdoMySqlTest.php
  - phpunit testsdb/PdoPostgresTest.php
