language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"

services:
  - docker

before_script:
  - npm i
  - node_modules/.bin/usdocker --refresh
  - node_modules/.bin/usdocker mysql up

install:
  - composer install

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/PdoMySqlTest.php

