language: php
php:
  - "7.1"

sudo: required

addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_script:
  - npm i
  - php -i
  - node_modules/.bin/usdocker --refresh
  - pecl istall
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apt install php-pgsql

install:
  - composer install
  - docker ps

script: 
  - phpunit
  - phpunit testsdb/PdoSqliteTest.php
  - phpunit testsdb/MongoDbDriverTest.php
  - phpunit testsdb/PdoMySqlTest.php
  - phpunit testsdb/PdoPostgresTest.php
